name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          profile: minimal
          override: true

      - name: cargo fmt -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Ensure cargo vendor works
        run: |
          cargo vendor
          rm -R vendor

  test:
    name: Test
    needs: [style]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Basic Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

      - name: Database Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: store_tests --all

      - name: JMAP Core Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: jmap_core_tests -- --ignored

      - name: JMAP Mail Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: jmap_mail_tests -- --ignored

      - name: Stress Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: jmap_stress_tests -- --ignored

      - name: Cluster Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: cluster_tests -- --ignored

